#!/bin/bash -xu

# This file is responsible for installing all the basic Ruby dependencies

script=`dirname $0`
script=`$script/_scriptdir`

install_rbenv () {
  git clone https://github.com/rbenv/rbenv.git ~/.rbenv
  cd ~/.rbenv && src/configure && make -C src
  echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
  ~/.rbenv/bin/rbenv init >> ~/.bash_profile
  source ~/.bash_profile
  git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
}

"$script/_has_command" rbenv || install_rbenv
